spring:
  # 数据库配置
  datasource:
    name: sonice1024
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.7.75:3306/gail?useSSL=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: mysql
    password: qRVimdEzatsf
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# Redis
  redis:
    timeout: 6000
    lettuce:
      pool:
        # 连接池最大连接数(-1表示不限制)
        max-active: 1000
        # 连接池最大阻塞等待时间(-1表示不限制, 单位毫秒ms)
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接, 默认为0
        min-idle: 100
        # 关闭连接前等待任务处理完成的最长时间, 默认为100ms
      shutdown-timeout: 100
    cluster:
      nodes:
        - 172.16.7.152:7000
        - 172.16.7.152:7001
        - 172.16.7.152:7002
        - 172.16.7.152:7003
        - 172.16.7.152:7004
        - 172.16.7.152:7005
      max-redirects: 3

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

#自封在应用配置
bx:
  # db:mybatis plus 配置
  mybatis-plus:
    # 租户隔离
    tenant:
      # 是否开启默认是关闭
      enable: false
      # 忽略表名 不区分大消息
      ignoreTables:
        - t_da
      # 忽略的mapperStatement
      ignoreMapperStatement:
        - com.aibaixun.mapper.TestMapper.selectById
        -
    # 自动填充
    fill:
      # 开启填充  默认开启
      enable: false
      # insert填充  默认开启
      enableInsertFill: false
      # update填充  默认开启
      enableUpdateFill: false
      # 创建时间字段
      createTimeField: true
      # 修改时间字段
      updateTimeField: true
    # 数据库类型
    dbType: MYSQL

  # swagger 配置
  swagger:
    # 开关
    enable: false
    title:
    description:
    version:
    basePackage:
    path:

gail:
  token-expired: 3600
  reflash-token-expired: 3600
